// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2fV0dxSRF375GrjcCU4lNjZJ7WYFJZLA',
    appId: '1:195843875330:web:42e10b7947f8bc89d0fd1b',
    messagingSenderId: '195843875330',
    projectId: 'carry-mark-assignment',
    authDomain: 'carry-mark-assignment.firebaseapp.com',
    storageBucket: 'carry-mark-assignment.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPrBNjTPMl_UCx9qGnf5MbVZ1D8B96lRg',
    appId: '1:195843875330:android:77787e3b897a827bd0fd1b',
    messagingSenderId: '195843875330',
    projectId: 'carry-mark-assignment',
    storageBucket: 'carry-mark-assignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb89_u9NQiuudaz7CQU_0nNP6BiaK9_Ak',
    appId: '1:195843875330:ios:e75f579ae214c28cd0fd1b',
    messagingSenderId: '195843875330',
    projectId: 'carry-mark-assignment',
    storageBucket: 'carry-mark-assignment.firebasestorage.app',
    iosBundleId: 'com.example.carryMarkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb89_u9NQiuudaz7CQU_0nNP6BiaK9_Ak',
    appId: '1:195843875330:ios:e75f579ae214c28cd0fd1b',
    messagingSenderId: '195843875330',
    projectId: 'carry-mark-assignment',
    storageBucket: 'carry-mark-assignment.firebasestorage.app',
    iosBundleId: 'com.example.carryMarkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2fV0dxSRF375GrjcCU4lNjZJ7WYFJZLA',
    appId: '1:195843875330:web:8e48f9a57e385685d0fd1b',
    messagingSenderId: '195843875330',
    projectId: 'carry-mark-assignment',
    authDomain: 'carry-mark-assignment.firebaseapp.com',
    storageBucket: 'carry-mark-assignment.firebasestorage.app',
  );
}
